### ISSUE TITLE
Relay are struggling to power on.

### ISSUE THREAD

**Issue by mhamidjamil** [mhamidjamil/Door-Monitoring#8]
When module got power from adopter ### relay struggle to switch to (adopter) power source, and it happened because when relay try to switch power source it loses power, so **there are 2 ways to fix it**.
_1: Use capacitor.
2: Use another pin to take this decision._

**Comment by SaffiUllah1999** [comment]
Still facing issue after updating hardware and software

**Comment by mhamidjamil** [comment]
you should try power bank 5v for collector pin, sorry I forget to mention it earlier.

**Comment by mhamidjamil** [comment]
Suitable version of project is deployed

**Comment by mhamidjamil** [comment]
> Suitable version of project is deployed
